version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_AUTH_METHOD: trust
    labels:
      com.symfony.server.service-prefix: 'DATABASE'
